[package]
name = "open_media_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
iced = "0.13.1"
mime_guess = "2.0.5"
open = "5.3.2"
ron = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
rfd = "0.15.2"
async-fs = "2.1.2"
iced_fonts = "0.1.1"
derive_more = { version = "1.0.0", features = ["deref", "deref_mut", "from"] }

[dependencies.iced_aw]
version = "0.11.0"
default-features = false
features = ["card"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = "symbols"
