[package]
name = "zcinema"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
iced = "0.12.1"
mime_guess = "2.0.4"
open = "5.1.2"
ron = "0.8.1"
serde = { version = "1.0.201", features = ["derive"] }
thiserror = "1.0.60"
rfd = "0.14.1"

[dependencies.iced_aw]
version = "0.9.3"
default-features = false
features = ["card", "modal"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = "symbols"
