[package]
name = "zcinema"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
iced = "0.12.1"
open = "5.1.2"
rfd = "0.14.1"
ron = "0.8.1"
serde = { version = "1.0.198", features = ["derive"] }
thiserror = "1.0.58"

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = "symbols"
