[package]
name = "zcinema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
iced = "0.12.1"
open = "5.1.2"
ron = "0.8.1"
serde = { version = "1.0.198", features = ["derive"] }
thiserror = "1.0.58"
