[package]
name = "open_media_tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
mime_guess = "2.0.5"
open = "5.3.2"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
rfd = "0.15.3"
async-fs = "2.1.2"
iced_fonts = "0.2.1"
fs-err = "3.1.0"
etcetera = "0.10.0"
serde_json = "1.0.140"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["winit"]

[dependencies.derive_more]
version = "2.0.1"
features = ["deref", "deref_mut", "display", "from"]

[dependencies.iced_aw]
version = "0.12.2"
default-features = false
features = ["card"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = "symbols"
panic = "abort"
