[package]
name = "zcinema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
iced = "0.12.1"
thiserror = "1.0.58"
