[package]
name = "open_media_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
iced = "0.13.1"
mime_guess = "2.0.5"
open = "5.3.0"
ron = "0.8.1"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.63"
rfd = "0.15.0"
async-fs = "2.1.2"

[dependencies.iced_aw]
version = "0.11.0"
default-features = false
features = ["card"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = "symbols"
